#!/bin/bash

force_monitor_off(){
	sleep 1
	xset dpms force off
}

is_docked(){
	[ "$(xrandr -q | grep '\<connected\>' | grep -v '\<eDP1\>' | wc -l)" -gt 0 ]
}

if ! is_docked; then
	force_monitor_off &
fi
i3lock --color 000000 --ignore-empty-password --show-failed-attempts
