#!/usr/bin/env python3

import sys


def percent_off(percent, price):
    return price - (price * (percent * 0.01))


if __name__=='__main__':
    if len(sys.argv) < 3:
        sys.exit(1)
    print(percent_off(float(sys.argv[1]), float(sys.argv[2])))

